// Auto-generated by a2r transpiler

use crate::db;
use crate::p2probe;
/// Note data model
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct Note {
    pub id: i64,
    pub title: String,
    pub body: String,
    pub time: String,
    pub pinned: bool,
    pub tags: &[String],
    pub folder: String,
}

/// 正文块。v1 只产生 text 块；checklist/asset/link 随 NOTES-002 扩展。
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct NoteBlock {
    pub kind: String,
    pub text: String,
    pub checked: bool,
}

/// NoteDocument v1：磁盘实体文件（notes/<note_id>.r<rev>.json）的完整内容。
/// 设计文档 §4 的超集：folder 为保留旧 UI 能力的扩展字段（记录于 Spec delta）；
/// created_at/updated_at 在无后端时钟能力期间为空串（显式缺失，T-00 §4）。
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct NoteDocument {
    pub schema_version: i64,
    pub note_id: String,
    pub revision: i64,
    pub title: String,
    pub blocks: &[NoteBlock],
    pub tags: &[String],
    pub color: String,
    pub pinned: bool,
    pub state: String,
    pub folder: String,
    pub created_at: String,
    pub updated_at: String,
    pub legacy_id: i64,
    pub seq: i64,
}

/// CaptureReceipt v1：request_id 幂等收据（receipts/<request_id>.json）。
/// 收据存在 ⇒ manifest 已含该提交（写入顺序保证，AC-02）。
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct CaptureReceipt {
    pub schema_version: i64,
    pub request_id: String,
    pub note_id: String,
    pub revision: i64,
    pub status: String,
}

/// 损坏条目（迁移打捞报告用）。
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct CorruptItem {
    pub index: i64,
    pub reason: String,
    pub snippet: String,
}

/// 迁移报告（corrupted/report-r1.json 持久化同一结构）。
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct MigrationReport {
    pub attempted: bool,
    pub migrated: i64,
    pub skipped_existing: bool,
    pub saved: bool,
    pub err: String,
    pub backup_file: String,
    pub corrupted: &[CorruptItem],
}

/// 仓储操作结构化结果：成功带文档/收据，失败带错误码。
/// err_code: "" | not_found | revision_conflict | storage_unwritable |
/// second_writer | corrupt | invalid_request | fault_injected
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct RepoResult {
    pub ok: bool,
    pub err_code: String,
    pub err_detail: String,
    pub doc: NoteDocument,
    pub receipt: CaptureReceipt,
}

pub fn v1_status() -> String {
    return db::v1_status();
}

pub fn v1_test_setup(data_dir: &str, legacy_file: &str) -> String {
    return db::v1_test_setup(data_dir, legacy_file);
}

pub fn v1_migrate() -> MigrationReport {
    return db::v1_migrate();
}

pub fn v1_create_note(request_id: &str, title: &str, body: &str, folder: &str) -> RepoResult {
    return db::v1_create_note(request_id, title, body, folder);
}

pub fn v1_update_note(nid: &str, expected_revision: i64, title: &str, body: &str, request_id: &str) -> RepoResult {
    return db::v1_update_note(nid, expected_revision, title, body, request_id);
}

pub fn v1_get_note(nid: &str) -> RepoResult {
    return db::v1_get_note(nid);
}

pub fn v1_trash_note(nid: &str) -> RepoResult {
    return db::v1_trash_note(nid);
}

pub fn v1_restore_note(nid: &str) -> RepoResult {
    return db::v1_restore_note(nid);
}

pub fn v1_list_notes() -> Vec<NoteDocument> {
    return db::v1_list_notes();
}

pub fn v1_test_fault(stage: &str) -> String {
    return db::v1_test_fault(stage);
}

pub fn v1_test_open() -> String {
    return db::v1_test_open();
}

pub fn v1_test_loadmanifest() -> String {
    return db::v1_test_loadmanifest();
}

pub fn v1_test_listloop() -> i64 {
    return db::v1_test_listloop();
}

pub fn list_notes() -> Vec<Note> {
    return db::all_notes();
}

pub fn get_note(id: i64) -> Option<Note> {
    return db::find_note(id);
}

pub fn create_note(title: &str, body: &str, folder: &str) -> Note {
    return db::create_note(title, body, folder);
}

pub fn update_note(id: i64, title: &str, body: &str) -> Option<Note> {
    return db::update_note(id, title, body);
}

pub fn delete_note(id: i64) -> bool {
    return db::delete_note(id);
}

pub fn toggle_pin(id: i64) -> Option<Note> {
    return db::toggle_pin(id);
}

pub fn update_tags(id: i64, tags: &[String]) -> Option<Note> {
    return db::update_tags(id, tags);
}

pub fn search_notes(query: &str) -> Vec<Note> {
    return db::search_notes(query);
}

pub fn p2_open() -> String {
    return p2probe::open_probe();
}

pub fn p2_txn() -> String {
    return p2probe::txn_probe();
}

pub fn p2_busy() -> String {
    return p2probe::busy_probe();
}

pub fn p2_rollback() -> String {
    return p2probe::rollback_probe();
}

pub fn p2_escape() -> String {
    return p2probe::escape_probe();
}
