// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use a2r_std;
use a2r_std::*;

use crate::api::{NoteDocument};
use crate::api::{MigrationReport};
use crate::api::{RepoResult};
use a2r_std::env;
use crate::repository;
use crate::p2probe;
pub fn v1_status() -> String {
    return repository::repo_status();
}

pub fn v1_test_setup(data_dir: &str, legacy_file: &str) -> String {
    a2r_std::env::set("NOTES_DATA_DIR", data_dir);
    a2r_std::env::set("NOTES_LEGACY_FILE", legacy_file);
    repository::test_reset();
    return "ok".to_string();
}

pub fn v1_migrate() -> MigrationReport {
    let mut legacy: String = a2r_std::env::get("NOTES_LEGACY_FILE");
    if legacy == "" {
        let mut d: String = repository::data_dir();
        legacy = format!("{}{}", d, "/notes.json");
    }
    return repository::migrate_legacy_at(legacy.as_str());
}

pub fn v1_create_note(request_id: &str, title: &str, body: &str, folder: &str) -> RepoResult {
    let mut tags: Vec<String> = List<str>.new(vec![]);
    return repository::repo_create(title, body, folder, tags, request_id.as_str());
}

pub fn v1_update_note(nid: &str, expected_revision: i64, title: &str, body: &str, request_id: &str) -> RepoResult {
    return repository::repo_update(nid, expected_revision, title, body, request_id);
}

pub fn v1_get_note(nid: &str) -> RepoResult {
    return repository::repo_get(nid);
}

pub fn v1_trash_note(nid: &str) -> RepoResult {
    return repository::repo_trash(nid);
}

pub fn v1_restore_note(nid: &str) -> RepoResult {
    return repository::repo_restore(nid);
}

pub fn v1_list_notes() -> Vec<NoteDocument> {
    return repository::repo_list_active();
}

pub fn v1_test_open() -> String {
    return repository::open_repository();
}

pub fn v1_test_loadmanifest() -> String {
    let mut ok: bool = repository::test_load_manifest();
    if ok {
        return "loaded".to_string();
    }
    return "load-failed".to_string();
}

pub fn v1_test_listloop() -> i64 {
    return repository::test_list_once();
}

pub fn v1_test_fault(stage: &str) -> String {
    if stage == "off" {
        a2r_std::env::set("NOTES_FAULT", "");
        return "off".to_string();
    }
    a2r_std::env::set("NOTES_FAULT", stage);
    return stage.to_string();
}

pub fn all_notes() -> Vec<NoteDocument> {
    return repository::repo_list_active();
}

pub fn find_note(id: i64) -> RepoResult {
    return repository::repo_get(repository::nid_of(id));
}

pub fn create_note(title: &str, body: &str, folder: &str) -> RepoResult {
    let mut tags: Vec<String> = List<str>.new(vec![]);
    return repository::repo_create(title, body, folder, tags, repository::ui_request_id("ui"));
}

pub fn update_note(id: i64, title: &str, body: &str) -> RepoResult {
    return repository::repo_get(repository::nid_of(id));
}

pub fn delete_note(id: i64) -> bool {
    let mut r = repository::repo_trash(repository::nid_of(id));
    return r.ok;
}

pub fn toggle_pin(id: i64) -> RepoResult {
    return repository::repo_get(repository::nid_of(id));
}

pub fn update_tags(id: i64, tags: &[String]) -> RepoResult {
    return repository::repo_set_tags(repository::nid_of(id), tags);
}

pub fn search_notes(query: &str) -> Vec<NoteDocument> {
    return repository::repo_search(query);
}

pub fn p2_open() -> String {
    return p2probe::open_probe();
}

pub fn p2_txn() -> String {
    return p2probe::txn_probe();
}

pub fn p2_busy() -> String {
    return p2probe::busy_probe();
}

pub fn p2_rollback() -> String {
    return p2probe::rollback_probe();
}

pub fn p2_escape() -> String {
    return p2probe::escape_probe();
}

fn doc_to_note(d: NoteDocument) -> impl Note {
    let mut body: String = "".to_string();
    if (d.blocks.len() as i64) > 0 {
        body = d.blocks[0].clone().text;
    }
    let mut t: String = d.updated_at.clone();
    if t == "" {
        t = "Just now".to_string();
    }
    let mut n: Note = Note { id: d.legacy_id, title: d.title, body: body, time: t, pinned: d.pinned, tags: d.tags, folder: d.folder };
    return n;
}

pub fn all_notes() -> Vec<Note> {
    let mut docs: Vec<NoteDocument> = repository::repo_list_active();
    let mut out: Vec<Note> = List<Note>.new(vec![]);
    for d in &docs {
        out.push(doc_to_note(d.clone()));
    }
    return out;
}

pub fn find_note(id: i64) -> Option<Note> {
    let mut r = repository::repo_get(repository::nid_of(id));
    if r.ok {
        let mut n: Note = doc_to_note(r.doc.clone());
        return Some(n);
    }
    return None;
}

pub fn create_note(title: &str, body: &str, folder: &str) -> impl Note {
    let mut tags: Vec<String> = List<str>.new(vec![]);
    let mut r = repository::repo_create(title, body, folder, tags, repository::ui_request_id("ui"));
    return doc_to_note(r.doc.clone());
}

pub fn update_note(id: i64, title: &str, body: &str) -> Option<Note> {
    let mut nid: String = repository::nid_of(id);
    let mut cur = repository::repo_get(nid.as_str());
    if cur.ok == false {
        return None;
    }
    let mut r = repository::repo_update(nid.as_str(), cur.doc.revision, title, body, repository::ui_request_id("ui-upd"));
    if r.ok {
        let mut n: Note = doc_to_note(r.doc.clone());
        return Some(n);
    }
    return None;
}

pub fn delete_note(id: i64) -> bool {
    let mut r = repository::repo_trash(repository::nid_of(id));
    return r.ok;
}

pub fn toggle_pin(id: i64) -> Option<Note> {
    let mut nid: String = repository::nid_of(id);
    let mut cur = repository::repo_get(nid.as_str());
    if cur.ok == false {
        return None;
    }
    let mut want: bool = cur.doc.pinned == false;
    let mut r = repository::repo_set_pinned(nid.as_str(), want);
    if r.ok {
        let mut n: Note = doc_to_note(r.doc.clone());
        return Some(n);
    }
    return None;
}

pub fn update_tags(id: i64, tags: &[String]) -> Option<Note> {
    let mut r = repository::repo_set_tags(repository::nid_of(id), tags);
    if r.ok {
        let mut n: Note = doc_to_note(r.doc.clone());
        return Some(n);
    }
    return None;
}

pub fn search_notes(query: &str) -> Vec<Note> {
    let mut docs: Vec<NoteDocument> = repository::repo_search(query);
    let mut out: Vec<Note> = List<Note>.new(vec![]);
    for d in &docs {
        out.push(doc_to_note(d.clone()));
    }
    return out;
}
