// Auto-generated by a2r transpiler

use crate::api::{NoteDocument};
use crate::api::{CaptureReceipt};
use crate::api::{NoteBlock};
use crate::api::{RepoResult};
pub fn probe_min() -> NoteDocument {
    let mut d: NoteDocument = NoteDocument { schema_version: 1, note_id: "".to_string(), revision: 0, title: "".to_string(), blocks: vec![], tags: vec![], color: "".to_string(), pinned: false, state: "".to_string(), folder: "".to_string(), created_at: "".to_string(), updated_at: "".to_string(), legacy_id: 0, seq: 0 };
    let mut rc: CaptureReceipt = CaptureReceipt { schema_version: 1, request_id: "".to_string(), note_id: "".to_string(), revision: 0, status: "".to_string() };
    let mut blk: NoteBlock = NoteBlock { kind: "".to_string(), text: "".to_string(), checked: false };
    d.blocks.push(blk.clone());
    return d;
}

pub fn probe_repo() -> RepoResult {
    let mut r: RepoResult = empty_stub();
    return r;
}

fn empty_stub() -> RepoResult {
    return empty_result_pub();
}
