// Auto-generated by a2r transpiler

// a2r Standard Library (from crate)
#[allow(unused_imports)]
use a2r_std;
use a2r_std::*;

use a2r_std::env;
use a2r_std::sqlite;
use a2r_std::json;
pub fn data_dir() -> String {
    let mut ov: String = a2r_std::env::get("NOTES_DATA_DIR");
    if ov != "" {
        return ov;
    }
    let mut base: String = a2r_std::env::get("APPDATA");
    if base == "" {
        base = a2r_std::env::get("XDG_DATA_HOME");
    }
    if base == "" {
        base = format!("{}{}", a2r_std::env::get("HOME"), "/.local/share");
    }
    if base == "" {
        base = ".".to_string();
    }
    return format!("{}{}", base, "/auto-notes/data");
}

pub fn db_path() -> String {
    return format!("{}{}", data_dir(), "/inbox.db");
}

fn parse_int(s: &str) -> i64 {
    let mut r: i64 = 0;
    let mut neg: bool = false;
    let mut i: i64 = 0;
    let mut n: i64 = (s.len() as i64);
    if n > 0 {
        let mut c0: i64 = s.chars().nth((0) as usize).unwrap_or('\0') as i64;
        if c0 == 45 {
            neg = true;
            i = 1;
        }    }
    while i < n {
        let mut cp: i64 = s.chars().nth((i) as usize).unwrap_or('\0') as i64;
        if cp != 0 {
            if cp >= 48 {
                if cp <= 57 {
                    r = r * 10 + cp - 48;
                }            }        }
        i = i + 1;
    }
    if neg {
        r = 0 - r;
    }
    return r;
}

fn note_cols() -> String {
    return "note_id, legacy_id, revision, title, body, tags_json, color, pinned, state, folder, seq, created_at, updated_at".to_string();
}

pub fn ui_request_id(prefix: &str) -> String {
    return format!("{}{}", format!("{}{}", prefix, "-"), serde_json::to_string(&next_counter()).unwrap_or_default());
}

pub fn nid_of(id: i64) -> String {
    return format!("{}{}", "n-", serde_json::to_string(&id).unwrap_or_default());
}

fn note_select_cols() -> String {
    return "note_id, legacy_id, revision, title, body, tags_json, color, pinned, state, folder, seq, created_at, updated_at".to_string();
}

pub fn open_repository() -> String {
    let mut db: a2r_std::sqlite::SqliteDb = open_conn();
    ensure_schema(db);
    return "".to_string();
}

pub fn read_receipt(request_id: &str) -> String {
    let mut rc: String = format!("{}{}", "{\"schema_version\":1,\"request_id\":", serde_json::to_string(&request_id).unwrap_or_default());
    rc = format!("{}{}", rc, ",\"note_id\":\"\",\"revision\":0,\"status\":\"\"}");
    if request_id == "" {
        return rc;
    }
    let mut db: a2r_std::sqlite::SqliteDb = open_conn();
    ensure_schema(db);
    let mut esc: String = serde_json::to_string(&request_id).unwrap_or_default();
    let mut sql: String = format!("{}{}", "SELECT note_id FROM requests WHERE request_id=", esc);
    let mut rows: Vec<Vec<String>> = db.query(sql);
    if (rows.len() as i64) < 1 {
        return rc;
    }
    let mut row = rows[0].clone();
    let mut nid: String = row[0].clone();
    rc = format!("{}{}", "{\"schema_version\":1,\"request_id\":", serde_json::to_string(&request_id).unwrap_or_default());
    rc = format!("{}{}", format!("{}{}", rc, ",\"note_id\":"), serde_json::to_string(&nid).unwrap_or_default());
    rc = format!("{}{}", rc, ",\"revision\":0,\"status\":\"committed\"}");
    return rc;
}

pub fn repo_create(title: &str, body: &str, folder: &str, tags_json: &str, request_id: &str) -> String {
    let mut oerr: String = open_repository();
    if oerr != "" {
        return format!("{}{}", format!("{}{}", "{\"ok\":false,\"err_code\":\"", oerr), "\"}");
    }
    let mut rid: String = request_id.to_string();
    if rid == "" {
        rid = ui_request_id("auto");
    }
    let mut db: a2r_std::sqlite::SqliteDb = open_conn();
    let mut begin: i64 = db.exec("BEGIN IMMEDIATE");
    if begin != 0 {
        return "{\"ok\":false,\"err_code\":\"second_writer\"}".to_string();
    }

    let mut dup = replay_in_txn(db.clone(), rid.as_str());
    if dup != "" {
        let mut finish: i64 = db.exec("COMMIT");
        return format!("{}{}", format!("{}{}", "{\"ok\":true,", dup[1..((dup.len() as i64) - 1) as usize].to_string()), ",\"replayed\":true}");
    }
    let mut handle: i64 = next_counter();
    let mut note_id: String = nid_of(handle);
    let mut seq: i64 = handle;
    let mut ins: i64 = db.exec(format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", "INSERT INTO notes(note_id, legacy_id, revision, title, body, tags_json, color, pinned, state, folder, seq, created_at, updated_at) VALUES(", serde_json::to_string(&note_id).unwrap_or_default()), ", "), serde_json::to_string(&handle).unwrap_or_default()), ", 1, "), serde_json::to_string(&title).unwrap_or_default()), ", "), serde_json::to_string(&body).unwrap_or_default()), ", '"), tags_json), "', 0, 'active', "), serde_json::to_string(&folder).unwrap_or_default()), ", "), serde_json::to_string(&seq).unwrap_or_default()), ", '', '')").as_str());
    if ins != 0 {
        db.exec("ROLLBACK");
        return "{\"ok\":false,\"err_code\":\"storage_unwritable\"}".to_string();
    }
    let mut ir: i64 = db.exec(format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", "INSERT OR IGNORE INTO requests(request_id, note_id, kind) VALUES(", serde_json::to_string(&rid).unwrap_or_default()), ", "), serde_json::to_string(&note_id).unwrap_or_default()), ", 'create')").as_str());
    if ir != 0 {
        db.exec("ROLLBACK");
        return "{\"ok\":false,\"err_code\":\"storage_unwritable\"}".to_string();
    }
    let mut bump: i64 = db.exec(format!("{}{}", format!("{}{}", format!("{}{}", "INSERT INTO meta(k,v) VALUES('counter',", serde_json::to_string(&handle + 1).unwrap_or_default()), ") ON CONFLICT(k) DO UPDATE SET v="), serde_json::to_string(&handle + 1).unwrap_or_default()).as_str());
    let mut commit: i64 = db.exec("COMMIT");
    if commit != 0 {
        return "{\"ok\":false,\"err_code\":\"storage_unwritable\"}".to_string();
    }
    let mut doc = load_doc_json_on(db.clone(), note_id.as_str());
    let mut rc: String = format!("{}{}", "{\"schema_version\":1,\"request_id\":", serde_json::to_string(&rid).unwrap_or_default());
    rc = format!("{}{}", format!("{}{}", format!("{}{}", rc, ",\"note_id\":"), serde_json::to_string(&note_id).unwrap_or_default()), ",\"revision\":1,\"status\":\"committed\"}");
    let mut out: String = format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", "{\"ok\":true,\"err_code\":\"\",\"note\":", doc), ",\"receipt\":"), rc), "}");
    return out;
}

pub fn repo_update(note_id: &str, expected_revision: i64, title: &str, body: &str, request_id: &str) -> String {
    let mut oerr: String = open_repository();
    if oerr != "" {
        return format!("{}{}", format!("{}{}", "{\"ok\":false,\"err_code\":\"", oerr), "\"}");
    }
    let mut rid: String = request_id.to_string();
    if rid == "" {
        rid = ui_request_id("auto-upd");
    }
    let mut db: a2r_std::sqlite::SqliteDb = open_conn();
    let mut begin: i64 = db.exec("BEGIN IMMEDIATE");
    if begin != 0 {
        return "{\"ok\":false,\"err_code\":\"second_writer\"}".to_string();
    }
    let mut dup = replay_in_txn(db.clone(), rid.as_str());
    if dup != "" {
        let mut fin: i64 = db.exec("COMMIT");
        return format!("{}{}", format!("{}{}", "{\"ok\":true,", dup[1..((dup.len() as i64) - 1) as usize].to_string()), ",\"replayed\":true}");
    }
    let mut rows: Vec<Vec<String>> = db.query(format!("{}{}", "SELECT revision FROM notes WHERE note_id=", serde_json::to_string(&note_id).unwrap_or_default()));
    if (rows.len() as i64) < 1 {
        db.exec("ROLLBACK");
        return "{\"ok\":false,\"err_code\":\"not_found\"}".to_string();
    }
    let mut row0 = rows[0].clone();
    let mut cur_rev: i64 = parse_int(row0[0].as_str());
    if cur_rev != expected_revision {
        db.exec("ROLLBACK");
        return format!("{}{}", format!("{}{}", "{\"ok\":false,\"err_code\":\"revision_conflict\",\"current_revision\":", serde_json::to_string(&cur_rev).unwrap_or_default()), "}");
    }
    let mut new_rev: i64 = expected_revision + 1;
    let mut upd: i64 = db.exec(format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", "UPDATE notes SET revision=", serde_json::to_string(&new_rev).unwrap_or_default()), ", title="), serde_json::to_string(&title).unwrap_or_default()), ", body="), serde_json::to_string(&body).unwrap_or_default()), " WHERE note_id="), serde_json::to_string(&note_id).unwrap_or_default()).as_str());
    if upd != 0 {
        db.exec("ROLLBACK");
        return "{\"ok\":false,\"err_code\":\"storage_unwritable\"}".to_string();
    }
    let mut ir: i64 = db.exec(format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", "INSERT OR IGNORE INTO requests(request_id, note_id, kind) VALUES(", serde_json::to_string(&rid).unwrap_or_default()), ", "), serde_json::to_string(&note_id).unwrap_or_default()), ", 'update')").as_str());
    if ir != 0 {
        db.exec("ROLLBACK");
        return "{\"ok\":false,\"err_code\":\"storage_unwritable\"}".to_string();
    }
    let mut commit: i64 = db.exec("COMMIT");
    if commit != 0 {
        return "{\"ok\":false,\"err_code\":\"storage_unwritable\"}".to_string();
    }
    let mut doc = load_doc_json_on(db.clone(), note_id);
    let mut rc: String = format!("{}{}", "{\"schema_version\":1,\"request_id\":", serde_json::to_string(&rid).unwrap_or_default());
    rc = format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", rc, ",\"note_id\":"), serde_json::to_string(&note_id).unwrap_or_default()), ",\"revision\":"), serde_json::to_string(&new_rev).unwrap_or_default()), ",\"status\":\"committed\"}");
    let mut out: String = format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", "{\"ok\":true,\"err_code\":\"\",\"note\":", doc), ",\"receipt\":"), rc), "}");
    return out;
}

pub fn repo_set_meta(mut note_id: &str, new_state: &str, pin: i64, mut tags_json: &str, set_tags: bool, mut folder: &str, set_folder: bool) -> String {
    let mut oerr: String = open_repository();
    if oerr != "" {
        return format!("{}{}", format!("{}{}", "{\"ok\":false,\"err_code\":\"", oerr), "\"}");
    }
    let mut cnt_rows: Vec<Vec<String>> = db_exists_note(note_id);
    if cnt_rows == 0 {
        return "{\"ok\":false,\"err_code\":\"not_found\"}".to_string();
    }
    let mut db: a2r_std::sqlite::SqliteDb = open_conn();
    let mut begin: i64 = db.exec("BEGIN IMMEDIATE");
    if begin != 0 {
        return "{\"ok\":false,\"err_code\":\"second_writer\"}".to_string();
    }
    if new_state != "" {
        db.exec(format!("{}{}", format!("{}{}", format!("{}{}", "UPDATE notes SET state=", serde_json::to_string(&new_state).unwrap_or_default()), " WHERE note_id="), serde_json::to_string(&note_id).unwrap_or_default()).as_str());
    }
    if pin >= 0 {
        db.exec(format!("{}{}", format!("{}{}", format!("{}{}", "UPDATE notes SET pinned=", serde_json::to_string(&pin).unwrap_or_default()), " WHERE note_id="), serde_json::to_string(&note_id).unwrap_or_default()).as_str());
    }
    if set_tags {
        db.exec(format!("{}{}", format!("{}{}", format!("{}{}", "UPDATE notes SET tags_json='", tags_json), "' WHERE note_id="), serde_json::to_string(&note_id).unwrap_or_default()).as_str());
    }
    if set_folder {
        db.exec(format!("{}{}", format!("{}{}", format!("{}{}", "UPDATE notes SET folder=", serde_json::to_string(&folder).unwrap_or_default()), " WHERE note_id="), serde_json::to_string(&note_id).unwrap_or_default()).as_str());
    }
    let mut commit: i64 = db.exec("COMMIT");
    if commit != 0 {
        return "{\"ok\":false,\"err_code\":\"storage_unwritable\"}".to_string();
    }
    let mut doc = load_doc_json_on(db.clone(), note_id);
    return format!("{}{}", format!("{}{}", "{\"ok\":true,\"note\":", doc), "}");
}

pub fn repo_trash(note_id: &str) -> String {
    return repo_set_meta(note_id, "trashed", -1, "[]", false, "", false);
}

pub fn repo_archive(note_id: &str) -> String {
    return repo_set_meta(note_id, "archived", -1, "[]", false, "", false);
}

pub fn repo_restore(note_id: &str) -> String {
    return repo_set_meta(note_id, "active", -1, "[]", false, "", false);
}

pub fn repo_set_pinned(note_id: &str, pinned: bool) -> String {
    let mut v: i64 = 0;
    if pinned {
        v = 1;
    }
    return repo_set_meta(note_id, "", v, "[]", false, "", false);
}

pub fn repo_set_tags(note_id: &str, tags_json: &str) -> String {
    return repo_set_meta(note_id, "", -1, tags_json, true, "", false);
}

pub fn repo_move(note_id: &str, folder: &str) -> String {
    return repo_set_meta(note_id, "", -1, "[]", false, folder, true);
}

pub fn repo_get(note_id: &str) -> String {
    let mut oerr: String = open_repository();
    if oerr != "" {
        return "".to_string();
    }
    let mut db: a2r_std::sqlite::SqliteDb = open_conn();
    return load_doc_json_on(db.clone(), note_id);
}

pub fn repo_list_active() -> String {
    let mut oerr: String = open_repository();
    if oerr != "" {
        return "[]".to_string();
    }
    let mut db: a2r_std::sqlite::SqliteDb = open_conn();
    let mut sql: String = format!("{}{}", format!("{}{}", "SELECT ", note_select_cols()), " FROM notes WHERE state='active' ORDER BY seq DESC");
    let mut rows: Vec<Vec<String>> = db.query(sql);
    let mut out: String = "[".to_string();
    let mut n: i64 = (rows.len() as i64);
    for k in 0..n {
        let mut row = rows[(k) as usize].clone();
        if k > 0 {
            out = format!("{}{}", out, ",");
        }
        out = format!("{}{}", out, row_to_doc_json(row.clone()));
    }
    out = format!("{}{}", out, "]");
    return out;
}

pub fn repo_search(query: &str) -> String {
    let mut oerr: String = open_repository();
    if oerr != "" {
        return "[]".to_string();
    }
    let mut like: String = format!("{}{}", format!("{}{}", "'%", query.to_lowercase()), "%'");
    let mut db: a2r_std::sqlite::SqliteDb = open_conn();
    let mut sql: String = format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", "SELECT ", note_select_cols()), " FROM notes WHERE state='active' AND (lower(title) LIKE '"), like), "' OR lower(body) LIKE '"), like), "') ORDER BY seq DESC");
    let mut rows: Vec<Vec<String>> = db.query(sql);
    let mut out: String = "[".to_string();
    let mut n: i64 = (rows.len() as i64);
    for k in 0..n {
        let mut row = rows[(k) as usize].clone();
        if k > 0 {
            out = format!("{}{}", out, ",");
        }
        out = format!("{}{}", out, row_to_doc_json(row.clone()));
    }
    out = format!("{}{}", out, "]");
    return out;
}

pub fn repo_status() -> String {
    let mut db: a2r_std::sqlite::SqliteDb = open_conn();
    ensure_schema(db);
    let mut rows: Vec<Vec<String>> = db.query("SELECT COUNT(*), COALESCE(MAX(CAST(legacy_id AS INTEGER)),0) FROM notes");
    let mut cnt: i64 = 0;
    let mut maxleg: i64 = 0;
    if (rows.len() as i64) > 0 {
        let mut row0 = rows[0].clone();
        cnt = parse_int(row0[0].as_str());
        maxleg = parse_int(row0[1].as_str());
    }
    let mut migrated: String = meta_get("migrated");
    let mut s: String = "{\"loaded\":true,\"err\":\"\",".to_string();
    s = format!("{}{}", format!("{}{}", s, "\"counter\":"), serde_json::to_string(&next_counter()).unwrap_or_default());
    s = format!("{}{}", format!("{}{}", s, ",\"entries\":"), serde_json::to_string(&cnt).unwrap_or_default());
    s = format!("{}{}", format!("{}{}", s, ",\"max_legacy_id\":"), serde_json::to_string(&maxleg).unwrap_or_default());
    s = format!("{}{}", format!("{}{}", s, ",\"migrated\":"), serde_json::to_string(&migrated).unwrap_or_default());
    s = format!("{}{}", format!("{}{}", s, ",\"data_dir\":"), serde_json::to_string(&data_dir()).unwrap_or_default());
    s = format!("{}{}", s, "}");
    return s;
}

/// 幂等创建：命中 requests → 返回原 note（AC-02）。
/// 返回 JSON：{"ok":..,"err_code":..,"note":{文档},"receipt":{...}}
/// 条件更新：expected_revision 不符 → revision_conflict（AC-04）。
/// 幂等重放先于 revision 检查（AC-02）。
/// 元数据变更（state/pinned/tags/folder）
/// 读取单个文档 JSON（含 trashed）；无 → ""
/// active 列表 JSON 数组，seq 降序（新在前）
/// 搜索：title/body 子串，大小写不敏感（SQL lower + LIKE）
/// 诊断状态
fn ensure_schema(db: a2r_std::sqlite::SqliteDb) {
    db.exec("PRAGMA busy_timeout=3000");
    db.exec("PRAGMA journal_mode=WAL");
    db.exec("CREATE TABLE IF NOT EXISTS notes(note_id TEXT PRIMARY KEY, legacy_id INTEGER UNIQUE, revision INTEGER NOT NULL DEFAULT 1, title TEXT NOT NULL DEFAULT '', body TEXT NOT NULL DEFAULT '', tags_json TEXT NOT NULL DEFAULT '[]', color TEXT NOT NULL DEFAULT '', pinned INTEGER NOT NULL DEFAULT 0, state TEXT NOT NULL DEFAULT 'active', folder TEXT NOT NULL DEFAULT '', seq INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT '', updated_at TEXT NOT NULL DEFAULT '')");
    db.exec("CREATE TABLE IF NOT EXISTS requests(request_id TEXT PRIMARY KEY, note_id TEXT NOT NULL, kind TEXT NOT NULL)");
    db.exec("CREATE TABLE IF NOT EXISTS meta(k TEXT PRIMARY KEY, v TEXT NOT NULL)");
}

fn open_conn() -> impl SqliteDb {
    let mut p: String = db_path();
    return a2r_std::sqlite::open(&p.as_str());
}

/// 按 note_id 载入文档 JSON；无 → ""
fn load_doc_json(db: a2r_std::sqlite::SqliteDb, note_id: &str) -> String {
    let mut esc: String = serde_json::to_string(&note_id).unwrap_or_default();
    let mut sql: String = format!("{}{}", format!("{}{}", format!("{}{}", "SELECT ", note_select_cols()), " FROM notes WHERE note_id="), esc);
    let mut rows: Vec<Vec<String>> = db.query(sql);
    if (rows.len() as i64) < 1 {
        return "".to_string();
    }
    let mut row = rows[0].clone();
    return row_to_doc_json(row.clone());
}

/// 行 → 文档 JSON（13 列固定序）
fn row_to_doc_json(row: Vec<String>) -> String {
    let mut s: String = format!("{}{}", "{\"schema_version\":1,\"note_id\":", serde_json::to_string(&row[0].clone()).unwrap_or_default());
    s = format!("{}{}", format!("{}{}", s, ",\"legacy_id\":"), row[1].clone());
    s = format!("{}{}", format!("{}{}", s, ",\"revision\":"), row[2].clone());
    s = format!("{}{}", format!("{}{}", s, ",\"title\":"), serde_json::to_string(&row[3].clone()).unwrap_or_default());
    s = format!("{}{}", format!("{}{}", s, ",\"body\":"), serde_json::to_string(&row[4].clone()).unwrap_or_default());
    s = format!("{}{}", format!("{}{}", s, ",\"tags\":"), row[5].clone());
    s = format!("{}{}", format!("{}{}", s, ",\"color\":"), serde_json::to_string(&row[6].clone()).unwrap_or_default());
    s = format!("{}{}", format!("{}{}", s, ",\"pinned\":"), row[7].clone());
    s = format!("{}{}", format!("{}{}", s, ",\"state\":"), serde_json::to_string(&row[8].clone()).unwrap_or_default());
    s = format!("{}{}", format!("{}{}", s, ",\"folder\":"), serde_json::to_string(&row[9].clone()).unwrap_or_default());
    s = format!("{}{}", format!("{}{}", s, ",\"seq\":"), row[10].clone());
    s = format!("{}{}", format!("{}{}", s, ",\"created_at\":"), serde_json::to_string(&row[11].clone()).unwrap_or_default());
    s = format!("{}{}", format!("{}{}", format!("{}{}", s, ",\"updated_at\":"), serde_json::to_string(&row[12].clone()).unwrap_or_default()), "}");
    return s;
}

fn note_select_cols() -> String {
    return "note_id, legacy_id, revision, title, body, tags_json, color, pinned, state, folder, seq, created_at, updated_at".to_string();
}

pub fn migrate_legacy_at(legacy_path: &str) -> String {
    let mut report: String = "{\"attempted\":true,\"migrated\":0,\"skipped_existing\":false,\"saved\":false,\"err\":\"\",\"backup_file\":\"\",\"corrupted\":[]}".to_string();
    let mut db: a2r_std::sqlite::SqliteDb = open_conn();
    ensure_schema(db.clone());
    let mut migrated_flag: String = meta_get("migrated");
    let mut cnt_sql: String = "SELECT COUNT(*) FROM notes".to_string();
    let mut cnt_rows: Vec<Vec<String>> = db.query(cnt_sql);
    let mut have: i64 = 0;
    if (cnt_rows.len() as i64) > 0 {
        let mut c0 = cnt_rows[0].clone();
        have = parse_int(c0[0].as_str());
    }
    if have > 0 || migrated_flag == "1" {
        return "{\"attempted\":true,\"migrated\":0,\"skipped_existing\":true,\"saved\":false,\"err\":\"\",\"backup_file\":\"\",\"corrupted\":[]}".to_string();
    }
    let mut ex: bool = fs_exists(legacy_path);
    if ex == false {
        return "{\"attempted\":false,\"migrated\":0,\"skipped_existing\":false,\"saved\":false,\"err\":\"\",\"backup_file\":\"\",\"corrupted\":[]}".to_string();
    }
    let mut raw: String = fs_read(legacy_path);
    if raw == "" {
        return "{\"attempted\":true,\"migrated\":0,\"skipped_existing\":false,\"saved\":false,\"err\":\"storage_unwritable\",\"backup_file\":\"\",\"corrupted\":[]}".to_string();
    }
    fs_mkdir(format!("{}{}", data_dir(), "/backup").as_str());
    let mut bdst: String = format!("{}{}", data_dir(), "/backup/notes.json.bak");
    let mut cpok: bool = fs_copy(legacy_path, bdst.as_str());
    if cpok == false {
        return "{\"attempted\":true,\"migrated\":0,\"skipped_existing\":false,\"saved\":false,\"err\":\"storage_unwritable\",\"backup_file\":\"\",\"corrupted\":[]}".to_string();
    }
    let mut valid: bool = a2r_std::json::is_valid(raw.as_str());
    let mut rows_json: String = "[]".to_string();
    if valid {
        rows_json = raw.to_string();
    } else {
        rows_json = salvage_objects(raw.as_str());
    }

    let mut rows: Vec<Vec<String>> = db.query(format!("{}{}", format!("{}{}", "SELECT '", rows_json.replace("'", "''")), "'"));


    let mut begin: i64 = db.exec("BEGIN IMMEDIATE");
    if begin != 0 {
        return format!("{}{}", format!("{}{}", "{\"attempted\":true,\"migrated\":0,\"skipped_existing\":false,\"saved\":false,\"err\":\"storage_unwritable\",\"backup_file\":\"", bdst), "\",\"corrupted\":[]}");
    }
    let mut arr = a2r_std::json::parse(rows_json.as_str());
    let mut n: i64 = (arr.len() as i64);
    let mut corrupted: String = "".to_string();
    let mut migrated_n: i64 = 0;
    let mut ids: String = "".to_string();
    for i in 0..n {
        let mut it = arr.get_at(i);
        let mut it_t: String = serde_json::to_string(&it).unwrap_or_default();
        let mut reason: String = "".to_string();
        if it_t == "null" {
            reason = "null entry".to_string();
        }
        if reason == "" {
            let mut idv = a2r_std::json::get(&it, "id");
            let mut idtxt: String = serde_json::to_string(&idv).unwrap_or_default();
            if idtxt == "null" {
                reason = "missing id".to_string();
            }            if reason == "" {
                let mut q1: String = idtxt[0..1].to_string();
                if q1 == "\"" {
                    reason = "id not an integer".to_string();
                }            }            if reason == "" {
                let mut hasdot: bool = a2r_std::str_contains(idtxt.as_str(), ".");
                if hasdot {
                    reason = "id not an integer".to_string();
                }            }            if reason == "" {
                let mut dup: bool = a2r_std::str_contains(ids.as_str(), format!("{}{}", format!("{}{}", ",", idtxt), ",").as_str());
                if dup {
                    reason = "duplicate id in source".to_string();
                }            }            if reason != "" {
                let mut sep: String = "".to_string();
                if (corrupted.len() as i64) > 0 {
                    sep = ",".to_string();
                }                corrupted = format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", corrupted, sep), "{\"index\":"), serde_json::to_string(&i).unwrap_or_default()), ",\"reason\":"), serde_json::to_string(&reason).unwrap_or_default()), "}");
            } else {
                let mut seq: i64 = handle_from_counter(db.clone());
                let mut title: String = a2r_std::json::as_string(&a2r_std::json::get(&it, "title"));
                let mut bodyv: String = a2r_std::json::as_string(&a2r_std::json::get(&it, "body"));
                let mut folder: String = a2r_std::json::as_string(&a2r_std::json::get(&it, "folder"));
                let mut pinned: i64 = 0;
                let mut pin_v = a2r_std::json::get(&it, "pinned");
                let mut pin_s: String = serde_json::to_string(&pin_v).unwrap_or_default();
                if pin_s == "true" {
                    pinned = 1;
                }                let mut ins: i64 = db.exec(format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", "INSERT INTO notes(note_id, legacy_id, revision, title, body, tags_json, pinned, state, folder, seq) VALUES(", serde_json::to_string(&format!("{}{}", "n-", idtxt)).unwrap_or_default()), ", "), idtxt), ", 1, "), serde_json::to_string(&title).unwrap_or_default()), ", "), serde_json::to_string(&bodyv).unwrap_or_default()), ", '"), tags_json_of(it)), "', "), serde_json::to_string(&pinned).unwrap_or_default()), ", 'active', "), serde_json::to_string(&folder).unwrap_or_default()), ", "), serde_json::to_string(&seq).unwrap_or_default()), ")").as_str());
                if ins != 0 {
                    db.exec("ROLLBACK");
                    return format!("{}{}", format!("{}{}", "{\"attempted\":true,\"migrated\":0,\"skipped_existing\":false,\"saved\":false,\"err\":\"storage_unwritable\",\"backup_file\":", serde_json::to_string(&bdst).unwrap_or_default()), ",\"corrupted\":[]}");
                }                ids = format!("{}{}", format!("{}{}", ids, ","), idtxt);
                migrated_n = migrated_n + 1;
            }
        }
    }
    let mut commit: i64 = db.exec("COMMIT");
    let mut saved_str: String = "true".to_string();
    let mut err_str: String = "".to_string();
    if commit != 0 {
        saved_str = "false".to_string();
        err_str = "storage_unwritable".to_string();
    }
    let mut out: String = format!("{}{}", "{\"attempted\":true,\"migrated\":", serde_json::to_string(&migrated_n).unwrap_or_default());
    out = format!("{}{}", format!("{}{}", out, ",\"skipped_existing\":false,\"saved\":"), saved_str);
    out = format!("{}{}", format!("{}{}", out, ",\"err\":"), serde_json::to_string(&err_str).unwrap_or_default());
    out = format!("{}{}", format!("{}{}", out, ",\"backup_file\":"), serde_json::to_string(&bdst).unwrap_or_default());
    out = format!("{}{}", format!("{}{}", format!("{}{}", out, ",\"corrupted\":["), corrupted), "]}");
    return out;
}

fn handle_from_counter(db: a2r_std::sqlite::SqliteDb) -> i64 {
    let mut sql: String = "SELECT COALESCE(MAX(CAST(legacy_id AS INTEGER)),0)+1 FROM notes".to_string();
    let mut rows: Vec<Vec<String>> = db.query(sql);
    let mut v: i64 = 1;
    if (rows.len() as i64) > 0 {
        let mut row0 = rows[0].clone();
        v = parse_int(row0[0].as_str());
    }
    let mut mrows: Vec<Vec<String>> = db.query("SELECT v FROM meta WHERE k='counter'");
    if (mrows.len() as i64) > 0 {
        let mut mrow = mrows[0].clone();
        let mut c: i64 = parse_int(mrow[0].as_str());
        if c > v {
            v = c;
        }    }
    return v;
}

fn fs_exists(p: &str) -> bool {
    return a2r_std::fs::exists(p);
}

fn fs_read(p: &str) -> String {
    return a2r_std::fs::read_text(&p);
}

fn fs_mkdir(p: &str) -> bool {
    return a2r_std::fs::create_dir(p);
}

fn fs_copy(a: &str, b: &str) -> bool {
    return a2r_std::fs::copy_recursive(a, b);
}

fn db_exists_note(note_id: &str) -> i64 {
    let mut db: a2r_std::sqlite::SqliteDb = open_conn();
    let mut sql: String = format!("{}{}", "SELECT note_id FROM notes WHERE note_id=", serde_json::to_string(&note_id).unwrap_or_default());
    let mut rows: Vec<Vec<String>> = db.query(sql);
    return (rows.len() as i64);
}

/// 括号配平打捞：截断 JSON 中提取完整对象（字节偏移扫描）
fn salvage_objects(raw: &str) -> String {
    let mut out: String = "[".to_string();
    let mut depth: i64 = 0;
    let mut obj_start: i64 = -1;
    let mut in_str: bool = false;
    let mut esc: bool = false;
    let mut byte_pos: i64 = 0;
    let mut n: i64 = (raw.len() as i64);
    for i in 0..n {
        let mut cp: i64 = raw.chars().nth((i) as usize).unwrap_or('\0') as i64;
        if cp != 0 {
            if in_str {
                if esc {
                    esc = false;
                } else {
                    if cp == 92 {
                        esc = true;
                    } else {
                        if cp == 34 {
                            in_str = false;
                        }                    }
                }
            } else {
                if cp == 34 {
                    in_str = true;
                } else {
                    if cp == 123 {
                        depth = depth + 1;
                        if depth == 1 {
                            obj_start = byte_pos;
                        }                    } else {
                        if cp == 125 {
                            if depth > 0 {
                                depth = depth - 1;
                                if depth == 0 {
                                    if obj_start >= 0 {
                                        let mut endb: i64 = byte_pos + 1;
                                        let mut piece: String = raw[(obj_start) as usize..(endb) as usize].to_string();
                                        if out != "[" {
                                            out = format!("{}{}", out, ",");
                                        }                                        out = format!("{}{}", out, serde_json::to_string(&piece).unwrap_or_default());
                                    }                                    obj_start = -1;
                                }                            }                        }                    }
                }
            }
            byte_pos = byte_pos + 1;
        }
    }
    out = format!("{}{}", out, "]");
    return out;
}

fn ensure_schema() {
    let mut db: a2r_std::sqlite::SqliteDb = a2r_std::sqlite::open(db_path().as_str());
    db.exec("PRAGMA busy_timeout=3000");
    db.exec("PRAGMA journal_mode=WAL");
    db.exec("CREATE TABLE IF NOT EXISTS notes(note_id TEXT PRIMARY KEY, legacy_id INTEGER UNIQUE, revision INTEGER NOT NULL DEFAULT 1, title TEXT NOT NULL DEFAULT '', body TEXT NOT NULL DEFAULT '', tags_json TEXT NOT NULL DEFAULT '[]', color TEXT NOT NULL DEFAULT '', pinned INTEGER NOT NULL DEFAULT 0, state TEXT NOT NULL DEFAULT 'active', folder TEXT NOT NULL DEFAULT '', seq INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT '', updated_at TEXT NOT NULL DEFAULT '')");
    db.exec("CREATE TABLE IF NOT EXISTS requests(request_id TEXT PRIMARY KEY, note_id TEXT NOT NULL, kind TEXT NOT NULL)");
    db.exec("CREATE TABLE IF NOT EXISTS meta(k TEXT PRIMARY KEY, v TEXT NOT NULL)");
}

fn meta_get(k: &str) -> String {
    let mut db: a2r_std::sqlite::SqliteDb = a2r_std::sqlite::open(db_path().as_str());
    let mut sql: String = format!("{}{}", "SELECT v FROM meta WHERE k=", serde_json::to_string(&k).unwrap_or_default());
    let mut rows: Vec<Vec<String>> = db.query(sql);
    if (rows.len() as i64) > 0 {
        let mut row0 = rows[0].clone();
        return row0[0].clone();
    }
    return "".to_string();
}

fn next_counter() -> i64 {
    let mut db: a2r_std::sqlite::SqliteDb = a2r_std::sqlite::open(db_path().as_str());
    let mut sql1: String = "SELECT COALESCE(MAX(CAST(legacy_id AS INTEGER)),0)+1 FROM notes".to_string();
    let mut rows: Vec<Vec<String>> = db.query(sql1);
    let mut v: i64 = 1;
    if (rows.len() as i64) > 0 {
        let mut row0 = rows[0].clone();
        v = parse_int(row0[0].as_str());
    }
    let mut mrows: Vec<Vec<String>> = db.query("SELECT v FROM meta WHERE k='counter'");
    if (mrows.len() as i64) > 0 {
        let mut mrow = mrows[0].clone();
        let mut c: i64 = parse_int(mrow[0].as_str());
        if c > v {
            v = c;
        }    }
    return v;
}

fn note_exists_db(note_id: &str) -> i64 {
    let mut db: a2r_std::sqlite::SqliteDb = a2r_std::sqlite::open(db_path().as_str());
    let mut sql: String = format!("{}{}", "SELECT note_id FROM notes WHERE note_id=", serde_json::to_string(&note_id).unwrap_or_default());
    let mut rows: Vec<Vec<String>> = db.query(sql);
    return (rows.len() as i64);
}

fn note_revision(note_id: &str) -> i64 {
    let mut db: a2r_std::sqlite::SqliteDb = a2r_std::sqlite::open(db_path().as_str());
    let mut sql: String = format!("{}{}", "SELECT revision FROM notes WHERE note_id=", serde_json::to_string(&note_id).unwrap_or_default());
    let mut rows: Vec<Vec<String>> = db.query(sql);
    if (rows.len() as i64) > 0 {
        return parse_int(rows[0].clone()[0].as_str());
    }
    return -1;
}

fn tags_json_of(it: i64) -> String {
    let mut tags_v = a2r_std::json::get(&it, "tags");
    if json.is_null() {
        return "[]".to_string();
    }
    let mut tj: String = serde_json::to_string(&tags_v).unwrap_or_default();
    let mut t1: String = tj[0..1].to_string();
    if t1 == "[" {
        return tj;
    }
    return "[]".to_string();
}

/// 事务内幂等重放：requests 命中 → 返回文档 JSON；未命中 → ""
fn replay_in_txn(db: a2r_std::sqlite::SqliteDb, rid: &str) -> String {
    if rid == "" {
        return "".to_string();
    }
    let mut esc: String = serde_json::to_string(&rid).unwrap_or_default();
    let mut sql: String = format!("{}{}", "SELECT note_id FROM requests WHERE request_id=", esc);
    let mut rows: Vec<Vec<String>> = db.query(sql);
    if (rows.len() as i64) < 1 {
        return "".to_string();
    }
    let mut row = rows[0].clone();
    return load_doc_json_on(db.clone(), row[0].as_str());
}

fn load_doc_json_on(db: a2r_std::sqlite::SqliteDb, note_id: &str) -> String {
    let mut esc: String = serde_json::to_string(&note_id).unwrap_or_default();
    let mut sql: String = format!("{}{}", format!("{}{}", format!("{}{}", "SELECT ", note_select_cols()), " FROM notes WHERE note_id="), esc);
    let mut rows: Vec<Vec<String>> = db.query(sql);
    if (rows.len() as i64) < 1 {
        return "".to_string();
    }
    let mut row = rows[0].clone();
    return row_to_doc_json(row.clone());
}

fn load_doc_json(note_id: &str) -> String {
    let mut db: a2r_std::sqlite::SqliteDb = a2r_std::sqlite::open(db_path().as_str());
    return load_doc_json_on(db.clone(), note_id);
}

pub fn test_list_once() -> i64 {
    let mut js: String = repo_list_active();
    let mut arr = a2r_std::json::parse(js.as_str());
    return (arr.len() as i64);
}
